routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', ['as' => 'home', 'uses' => 'PlayerCompetitionsController@index']);
Route::get('/competitions/{id}', ['as' => 'competition_field', 'uses' => 'PlayerCompetitionsController@show']);
Route::get('/competitions/{id}/teams', 'PlayerCompetitionsController@showTeams');
Route::get('/competitions/{id}/join', 'PlayerCompetitionsController@create');
Route::get('/competitions/{id}/contact', 'PlayerCompetitionsController@showContact');
Route::get('/competitions/{id}/draws','PlayerCompetitionsController@showDraws');
Route::post('/competitions/join', 'PlayerCompetitionsController@store');

Auth::routes();

Route::get('/admin', function () {
    return redirect('login');
});

Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'web', 'auth']], function () {

    Route::resource('competitions', 'AdminCompetitionsController');
    Route::resource('users', 'AdminUsersController');
    Route::get('competitions/{competition_id}/edit_rego', 'AdminCompetitionsController@edit_rego')->name('competitions.edit_rego');

    // !!! DIFFERENT ADMIN PANEL FOR USER POSTS
    Route::group(['prefix' => 'competitions/{competition_id}'], function () {
        Route::resource('contacts', 'AdminContactsController');
        Route::resource('details', 'AdminDetailsController');
        Route::resource('players', 'AdminPlayersController');
        Route::resource('teams', 'AdminTeamsController');
        Route::resource('matches', 'AdminMatchesController');
        Route::get('players/export/{id}', 'ExcelController@export');
        Route::post('matches/store_automatic', 'AdminMatchesController@store_automatic');
        Route::get('matches/autocreate/{id}', 'AdminMatchesController@autoCreate');
        Route::get('matches/clear/{id}', 'AdminMatchesController@clear');
        Route::get('matches/destroy/{match_id}', 'AdminMatchesController@destroy');

    });
});

app/Competition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Competition extends Model
{
    protected $fillable = [
        'name', 'rego_open', 'rego_close'
    ];

    protected $dates = ['created_at', 'updated_at', 'rego_open', 'rego_close'];


    public function contacts(){
        return $this->hasMany('App\Contact');
    }

    public function details(){
        return $this->hasMany('App\Detail');
    }

    public function teams(){
        return $this->hasMany('App\Team');
    }

        public function players(){
        return $this->hasMany('App\Player');
    }

    public function matches(){
        return $this->hasMany('App\Match');
    }

}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Laratrust\Traits\LaratrustUserTrait;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'is_admin',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];


    public function isAdmin(){
        if($this->is_admin == 1){
            return true;
        }

        return false;


    }
}

app/Http/Controllers/CompetitionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Competition;
use Auth;

class CompetitionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $current_user_id = Auth::user()->id;
        $competitions = Competition::where('establisher', $current_user_id)->get();
        return view('home', compact('competitions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'competitionName'=>'required'
        ]);

        $competition = new Competition;
        $competition->name = $request->input('competitionName');
        $competition->establisher = Auth::user()->id;
        
        // avoid repeated submit
        $oldCompetitions = Competition::where('name', $competition->name)->get();
        foreach($oldCompetitions as $oldCompetition){
            if($oldCompetition->establisher == $competition->establisher){
                $current_user_id = Auth::user()->id;
                $competitions = Competition::where('establisher', $current_user_id)->get();
                
                // should return error message!!! 
                return view('home', compact('competitions'));
            }
        }
        
        $competition->save();
        $current_user_id = Auth::user()->id;
        $competitions = Competition::where('establisher', $current_user_id)->get();
        return view('home', compact('competitions'));
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $competition = Competition::find($id);

        return view('competition.show')->with('competition',$competition);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/competitions/users/edit.blade.php
@extends('layouts.admin')

@section('content')

    <h1>{{$user->name}}</h1>


            {!! Form::model($user, ['method'=>'PATCH', 'action' =>['AdminUsersController@update', $user->id], 'files' => true]) !!}

            {{--<div class="form-group">--}}
                {{--{!! Form::label('name','Name:') !!}--}}
                {{--{!! Form::text('name',null, ['class' =>'form-control']) !!}--}}
            {{--</div>--}}

            {{--<div class="form-group">--}}
                {{--{!! Form::label('email','Email:') !!}--}}
                {{--{!! Form::email('email',null, ['class' =>'form-control']) !!}--}}
            {{--</div>--}}

            <div class="form-group">
                {!! Form::label('is_admin','Status:') !!}
                {!! Form::select('is_admin',array(0 => 'Not Admin',1=>'Admin' ), null, ['class' =>'form-control']) !!}
            </div>


            {{--<div class="form-group">--}}
                {{--{!! Form::label('password','Password:') !!}--}}
                {{--{!! Form::password('password', ['class' =>'form-control']) !!}--}}
            {{--</div>--}}


            <div class="form-group">
                {!! Form::submit('Update user', ['class'=>'btn btn-primary col-sm-6']) !!}
            </div>

            {!! Form::close() !!}


            {!! Form::open(['method'=>'DELETE', 'action' =>['AdminUsersController@destroy', $user->id]]) !!}

            <div class="form-group">
                {!! Form::submit('Delete user', ['class'=>'btn btn-danger col-sm-6']) !!}
            </div>

    {!! Form::close() !!}


    <div class="row">
        @include('includes.form_error')
    </div>

@stop

resources/views/admin/competitions/users/index.blade.php
@extends('layouts.admin')

@section('content')

    <h1>Users</h1>

    <table class="table">
        <thead>
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Role</th>
            <th>Created</th>
            <th>Updated</th>

        </tr>
        </thead>
        <tbody>

        @if($users)
            @foreach($users as $user)
                <tr>
                    <td>{{$user->id}}</td>

                    <td><a href="{{route('users.edit', $user->id)}}">{{$user->name}}</a></td>
                    <td>{{$user->email}}</td>
                    <td>{{$user->is_admin == 1? 'Admin': 'Not Admin'}}</td>
                    <td>{{$user->created_at->diffForHumans()}}</td>
                    <td>{{$user->updated_at->diffForHumans()}}</td>

                </tr>
            @endforeach

        @endif
        </tbody>
    </table>





@stop