routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
 */

Route::get('/', ['as' => 'home', 'uses' => 'PlayerCompetitionsController@index']);
Route::get('/competitions/{id}', ['as' => 'competition_field', 'uses' => 'PlayerCompetitionsController@show']);
Route::get('/competitions/{id}/teams', 'PlayerCompetitionsController@showTeams');
Route::get('/competitions/{id}/join', 'PlayerCompetitionsController@create');
Route::get('/competitions/{id}/contact', 'PlayerCompetitionsController@showContact');
Route::get('/competitions/{id}/draws','PlayerCompetitionsController@showDraws');
Route::post('/competitions/join', 'PlayerCompetitionsController@store');

Auth::routes();

Route::get('/admin', function () {
    return redirect('login');
});

Route::group(['prefix' => 'admin', 'middleware' => ['admin', 'web', 'auth']], function () {

    Route::resource('competitions', 'AdminCompetitionsController');
    Route::resource('users', 'AdminUsersController');
    Route::get('competitions/{competition_id}/edit_rego', 'AdminCompetitionsController@edit_rego')->name('competitions.edit_rego');

    // !!! DIFFERENT ADMIN PANEL FOR USER POSTS
    Route::group(['prefix' => 'competitions/{competition_id}'], function () {
        Route::resource('contacts', 'AdminContactsController');
        Route::resource('details', 'AdminDetailsController');
        Route::resource('players', 'AdminPlayersController');
        Route::resource('teams', 'AdminTeamsController');
        Route::resource('matches', 'AdminMatchesController');
        Route::get('players/export/{id}', 'ExcelController@export');
        Route::post('matches/store_automatic', 'AdminMatchesController@store_automatic');
        Route::get('matches/autocreate/{id}', 'AdminMatchesController@autoCreate');
        Route::get('matches/clear/{id}', 'AdminMatchesController@clear');
        Route::get('matches/destroy/{match_id}', 'AdminMatchesController@destroy');

    });
});

app/Competition.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Competition extends Model
{
    protected $fillable = [
        'name', 'rego_open', 'rego_close'
    ];

    protected $dates = ['created_at', 'updated_at', 'rego_open', 'rego_close'];


    public function contacts(){
        return $this->hasMany('App\Contact');
    }

    public function details(){
        return $this->hasMany('App\Detail');
    }

    public function teams(){
        return $this->hasMany('App\Team');
    }

        public function players(){
        return $this->hasMany('App\Player');
    }

    public function matches(){
        return $this->hasMany('App\Match');
    }

}

app/Http/Controllers/CompetitionController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Competition;
use Auth;

class CompetitionController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $current_user_id = Auth::user()->id;
        $competitions = Competition::where('establisher', $current_user_id)->get();
        return view('home', compact('competitions'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request,[
            'competitionName'=>'required'
        ]);

        $competition = new Competition;
        $competition->name = $request->input('competitionName');
        $competition->establisher = Auth::user()->id;
        
        // avoid repeated submit
        $oldCompetitions = Competition::where('name', $competition->name)->get();
        foreach($oldCompetitions as $oldCompetition){
            if($oldCompetition->establisher == $competition->establisher){
                $current_user_id = Auth::user()->id;
                $competitions = Competition::where('establisher', $current_user_id)->get();
                
                // should return error message!!! 
                return view('home', compact('competitions'));
            }
        }
        
        $competition->save();
        $current_user_id = Auth::user()->id;
        $competitions = Competition::where('establisher', $current_user_id)->get();
        return view('home', compact('competitions'));
        
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $competition = Competition::find($id);

        return view('competition.show')->with('competition',$competition);
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/competitions/create.blade.php
@extends('layouts.admin')

@section('content')
<br>

<h3>Create a competition</h3>


    {!! Form::open(['method'=>'POST', 'action' =>'AdminCompetitionsController@store', 'files' => true]) !!}

    <div class="form-group">
        {!! Form::label('name','Name') !!}
        {!! Form::text('name',null, ['class' =>'form-control']) !!}
    </div>



    <input type="hidden" id="rego_open" name="rego_open" value="{{$now}}">
    <input type="hidden" id="rego_close" name="rego_close" value="{{$now}}">



    <div class="form-group">
        {!! Form::submit('Create competition', ['class'=>'btn btn-primary col-sm-6']) !!}
    </div>

    {!! Form::close() !!}


    <div class="row">
        @include('includes.form_error')
    </div>

@stop

resources/views/admin/competitions/edit.blade.php
@extends('layouts.admin')

@section('content')

    <br>
    <h3 class="float-left">{{ $competition->name}}/Edit or delete competition</h3>

    <div class="float-right">
        <a href="{{ Request::url()}}/create" class="button btn btn-info"><i class="fa fa-plus-square"></i>  Add a player</a>

    </div>



    @include('admin.competitions.layouts.navbar')




    {!! Form::model($competition, ['method'=>'PATCH', 'action' =>['AdminCompetitionsController@update', $competition->id], 'files' => true]) !!}

    <div class="form-group">
        {!! Form::label('name','Name') !!}
        {!! Form::text('name',null, ['class' =>'form-control']) !!}
    </div>

    {{--<div class="form-group">--}}
        {{--{!! Form::label('rego_open','Registration open') !!}--}}
        {{--{!! Form::datetime('rego_open',null, ['class' =>'form-control']) !!}--}}
    {{--</div>--}}


    {{--<div class="form-group">--}}
        {{--{!! Form::label('rego_close','Registration close') !!}--}}
        {{--{!! Form::datetime('rego_close',null, ['class' =>'form-control']) !!}--}}
    {{--</div>--}}



    <div class="form-group">
        {!! Form::submit('Update contact', ['class'=>'btn btn-primary col-sm-6']) !!}
    </div>

    {!! Form::close() !!}



    {!! Form::open(['method'=>'DELETE', 'action' =>['AdminCompetitionsController@destroy', $competition->id]]) !!}

    <div class="form-group">
        {!! Form::submit('Delete contact', ['class'=>'btn btn-danger col-sm-6']) !!}
    </div>

    {!! Form::close() !!}



    <div class="row">
        @include('includes.form_error')
    </div>


@stop

resources/views/admin/competitions/edit_rego.blade.php
@extends('layouts.admin')

@section('content')<br>


<br>
<h3 class="float-left">{{ $competition->name}}/Edit registration dates</h3>

<div class="float-right">

</div>

@include('admin.competitions.layouts.navbar')




    {!! Form::model($competition, ['method'=>'PATCH', 'action' =>['AdminCompetitionsController@update', $competition->id], 'files' => true]) !!}


    <input type="hidden" id="name" name="name" value="{{$competition->name}}">


    <div class="form-group">
    {!! Form::label('rego_open','Registration open') !!}
    {!! Form::datetime('rego_open',null, ['class' =>'form-control']) !!}
    </div>


    <div class="form-group">
    {!! Form::label('rego_close','Registration close') !!}
    {!! Form::datetime('rego_close',null, ['class' =>'form-control']) !!}
    </div>


    <div class="form-group">
        {!! Form::submit('Update registration period', ['class'=>'btn btn-primary col-sm-6']) !!}
    </div>

    {!! Form::close() !!}




@stop

resources/views/admin/competitions/index.blade.php
@extends('layouts.admin')

@section('content')
    <br>

    <h3 class="float-left">Competitions</h3>


    <div class="float-right">

    <a href="{{route('users.index')}}" class="button btn btn-info"><i class="fas fa-user"></i> Users</a>
    <a href="{{route('competitions.create')}}" class="button btn btn-info"><i class="fa fa-plus-square"></i> Create a competition</a>

    </div>
    <div class="table-responsive">

        <table class="table">
            <thead>
            <tr>
                <th>Name</th>
                <th>Registration close</th>

            </tr>
            </thead>
            <tbody>

            @if($competitions)
                @foreach($competitions as $competition)
                    <tr>
                        <td class="text-nowrap"><a href="{{ Request::url().'/'.$competition->id }}/players">{{$competition->name}}</a></td>
                        <td class="text-nowrap">{{$competition->rego_close->diffForhumans()}}</td>
                    </tr>
                @endforeach
            @endif
            </tbody>
        </table>


    </div>


@stop